# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Digital Repository
author: T. Haposan
logo: logo.png # logo vector is from Iconiic at Flaticon

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: repo.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/executablebooks/jupyter-book  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  home_page_in_navbar: false
  #announcement: "👷‍♂️ As we are just launching this course, the content keeps updating! Please check back regularly for updates."
  extra_footer          : |
    <p>
    <img src='https://mirrors.creativecommons.org/presskit/buttons/88x31/svg/by-sa.svg' height='31'/>
    </br> © Copyright 2025 T. Haposan unless stated | <a href='https://haposan.com'>haposan.com</a>
    </br>Powered by <a href="https://jupyterbook.org">Jupyter Book</a>
    </p>
  extra_navbar          : ''
